In [ ]:
import numpy as np 
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
from google.colab import files
uploded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (1).csv


In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploded['Churn_Modelling.csv']))
df.shape

(10000, 14)

In [ ]:
df.drop(['CustomerId','RowNumber','Surname'], axis = 'columns', inplace =True)

df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [ ]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
#one hot encoding
df = pd.get_dummies(data = df, columns=['Geography'])
df.dtypes

CreditScore            int64
Gender                object
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Exited                 int64
Geography_France       uint8
Geography_Germany      uint8
Geography_Spain        uint8
dtype: object

In [ ]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
df['Gender'].replace(['Male', 'Female'],[1, 0], inplace= True)
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [ ]:
#separate outcome or target col
X = df.drop(['Exited'], axis=1)
y = df['Exited']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
#
# feature scaling
#
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(12, input_shape=(12,),activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)

model.evaluate(X_test, y_test)

yp = model.predict(X_test)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7484
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4420 - accuracy: 0.8094
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4242 - accuracy: 0.8183
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4142 - accuracy: 0.8240
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4059 - accuracy: 0.8284
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3951 - accuracy: 0.8345
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3809 - accuracy: 0.8430
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3672 - accuracy: 0.8511
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3574 - accuracy: 0.8568
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3506 - accura

In [ ]:
from sklearn.metrics import confusion_matrix
#from sklearn.metrics import classification_report
#print(classification_report(y_test,yp))
y_pred = []
for element in yp:
    if element > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [ ]:
#print(classification_report(y_test,y_pred))


In [ ]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_pred)
cm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1516,   79],
       [ 201,  204]], dtype=int32)>

In [ ]:
tf.math.confusion_matrix(labels=y_test,predictions=y_pred)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1516,   79],
       [ 201,  204]], dtype=int32)>